services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/telebash/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    env_file:
      - .env
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  open-webui: {}
